# Generated by Django 5.2.11 on 2026-03-07 20:37

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=station.models.station_image_file_path
            ),
        ),
    ]
