# Generated by Django 5.2.11 on 2026-03-07 21:16

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_station_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.station_image_file_path
            ),
        ),
    ]
